[package]
name = "json"
version = "0.1.0"
authors = ["Drew"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
erased-serde = "0.3"
anyhow = "1.0"
